### ISSUE TITLE
Setup info is incomplete

### ISSUE THREAD

**Issue by jpcrumley** [julianfez/homebridge-augustlock2#2]
I have installed the plugin but nowhere am I prompted to login.  There is also no information on what is needed to update the config.json file for homebridge.

**Comment by julianfez** [comment]
The homebridge api v2 dont requires setup on the config  you can read the closed issues someone already ask the same

**Comment by jpcrumley** [comment]
I did read the closed issue and the problem is the august lock never even shows up.

**Comment by julianfez** [comment]
Which application are you using? To setup august

**Comment by jpcrumley** [comment]
I have the August app to run it normally, but for Homekit I've tried both Hesperus and the iOS 10 Home app

**Comment by julianfez** [comment]
With the Hesperus app go to accessories slide left your bridge and manage platform and follow the instructions

**Comment by jpcrumley** [comment]
It doesn't even see the August lock

**Comment by jpcrumley** [comment]
I was able to get the section up to enter in the information but I'm not getting a text with the verification code.

**Comment by bryangauvin** [comment]
Same, No documentation. Were you ever able to figure out how to get the text? @jpcrumley @julianfez
